# Generated by Django 5.0.1 on 2024-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_show_description_job_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='linkedin_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
