# Generated by Django 5.0.1 on 2024-01-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_linkedin_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='linkedin_job_id',
            new_name='linkedin_job_link',
        ),
    ]
