# Generated by Django 5.0.1 on 2024-01-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_linkedin_job_id_job_linkedin_job_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='linkedin_job_link',
        ),
    ]
