# Generated by Django 5.0.1 on 2024-01-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
