# Generated by Django 5.0.1 on 2024-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_access_token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
